### PR TITLE
feat: ast scanning.

### PR DESCRIPTION
**Pull request by llllllllll**
This feature adds a step to the generation process that scans the files for illegal tokens. This allows us to warn the user that their code will not run on Quantopian before they send it to the browser IDE. This also gives line and column numbers in the ORIGINAL file that the code was seen, not in the final product. This lets the user fix the source of the issue. These are only emitted as warnings and will not stop the build process from completing.

This tries to provide a framework so that you may add new tokens to the warnings set as you see fit.

### CODE REVIEW

**Comment by florentchandelier** [comment]
Hi, thanks for the contrib. I've created a new branch for it.
could you provide some examples of what is corrected by your proposal, I have not been able to modify the current example strategy so that it does trigger your module during quantopian script generation.

thanks.

**Comment by llllllllll** [comment]
When you ran it, was ast_scan.py in your $PATH? as a test, take psw_core.py and put an eval('2 + 2') somewhere.

**Comment by llllllllll** [comment]
ping @florentchandelier

**Comment by florentchandelier** [comment]
I'll keep the request open until I feel the overall script is mature enough, and then add extra depencies. Although warnings for code not running on quantopian is definitely interesting, it's simply a matter for one to check that directly in Q by running a backtest.

**Pull request closed without merging**
